[project]
name = "telegram-bot"
version = "0.1.0"
description = "AI Devtools Hack Bot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.23.0",
    "openai>=2.9.0",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
]
